### ISSUE TITLE
ROS node setup error

### ISSUE THREAD

**Issue by yukkysaito** [maudzung/SFA3D#11] opened 2020-09-07 05:49 UTC
I believe that python 2.7 is standard in ROS melodic, but pip install asks for pip3.
Please let me know if you have any ideas.

Environment
- ubuntu 18.04
- ros melodic

```
~/workspace/catkin_ws/src/SFA3D master
❯ pip install .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Processing /home/yukihiro/workspace/catkin_ws/src/SFA3D
ERROR: Package 'sfa' requires a different Python: 2.7.17 not in '>=3.6.0'

```

**Comment by maudzung** [comment] 2020-09-07 06:00
hi @yukkysaito 

Actually, I have created a virtual environment with only python3.6, so I can use `pip install .`
You can try `pip3 install .`

**Comment by maudzung** [comment] 2020-09-07 08:59
Hi @yukkysaito 
How is it going? If it works, please close the issue. Otherwise, we can help you to solve it. @AhmedARadwan

**Comment by AhmedARadwan** [comment] 2020-09-07 13:28
Hi @yukkysaito, Can you try using ``` pip3 install . ``` after the installation of pytorch?

**Comment by maudzung** [comment] 2020-09-08 09:35
It's not an issue of the source code.

**Comment by nullket** [comment] 2020-09-18 05:30
This might not be a problem with the source itself, but with the README of the ROS part and therefore it is still a bug and should be reopend: 

The ros README states that on Ubuntu 18.04 and with rosmelodic you would only need to run `pip install .` in order to install the dependencies. But in 18.04 the standard `python` interpreter is `2.7` and therefore `pip` tries to install dependencies for  2.7. but fails as `setup.py`of SFA3D requires `>=3.6` 

Ubuntu 18.04 ships with python 3.6 as `python3` with `pip3`. Simply using `pip3 install .` works for installing the packages but it would be still not possible to run it with standard ROS Meldoic (which is by design meant to be python2 only). There are hacky ways on how to execute a python3 code within ros. But those sould be explained in the `README`. I have setup a virtualenv trying to solve the problem. It kinda worked but I got not objects published (might be another bug/misconfiguration by myself). Anyway, the `README` is missing what @AhmedARadwan actually did from a clean system to get this working. It would be very  great if you could check that.

**Comment by maudzung** [comment] 2020-09-23 23:07
Thanks @nullket 
@AhmedARadwan Can you check the issue and update the instructions in README?

**Comment by AhmedARadwan** [comment] 2020-09-24 00:00
@maudzung okay I'll edit the README asap

**Closed** 2020-10-17 00:25 UTC
